/* lqr_gains.h — 3-term LQR gains (3-state + wo 一阶惯性), auto-generated by gen_lqr.py */
/* Model: [ey,eth,eth_d], Δδ → car yaw accel via -wo·eth_d - wo·v/L·Δδ */
/* K_stored = -K_riccati, code: u_fb = +K_stored·x, δ_cmd = δ_vst + Δδ_fb */
/* Cost: J = 20.0*ey^2 + 0.0*eth^2 + 0.0*eth_d^2 + 1.0*Δδ^2, wo=15.0 */
/* L=0.15m, v=[0.1,5.0]m/s, n=11 */
#ifndef LQR_GAINS_H
#define LQR_GAINS_H
#include "common.h"

#define LQR_SPEED_POINTS 11

static const f32 lqr_speed_bp[] = {0.1f, 0.5f, 1.0f, 1.5f, 2.0f, 2.5f, 3.0f, 3.5f, 4.0f, 4.5f, 5.0f};
static const f32 lqr_gains[11][3] = {
    {    4.472136f,     1.187723f,     0.077195f},  /* v=0.1 */
    {    4.472136f,     1.297979f,     0.076722f},  /* v=0.5 */
    {    4.472136f,     1.420622f,     0.075638f},  /* v=1.0 */
    {    4.472136f,     1.529344f,     0.074331f},  /* v=1.5 */
    {    4.472136f,     1.626936f,     0.072967f},  /* v=2.0 */
    {    4.472136f,     1.715568f,     0.071623f},  /* v=2.5 */
    {    4.472136f,     1.796881f,     0.070330f},  /* v=3.0 */
    {    4.472136f,     1.872121f,     0.069101f},  /* v=3.5 */
    {    4.472136f,     1.942245f,     0.067939f},  /* v=4.0 */
    {    4.472136f,     2.008002f,     0.066844f},  /* v=4.5 */
    {    4.472136f,     2.069987f,     0.065812f},  /* v=5.0 */
};

#endif
